const API_BASE_URL_SPOTIFY = 'https://api.napster.com'
const API_AUTHORIZE_URL_SPOTIFY = 'https://accounts.spotify.com'
const API_BASE_VERSION_SPOTIFY = ''
const API_CLIENT_ID_SPOTIFY = 'd6636f756899487ba94e943b49289c47'

export default {
  API_BASE_URL_SPOTIFY,
  API_AUTHORIZE_URL_SPOTIFY,
  API_BASE_VERSION_SPOTIFY,
  API_CLIENT_ID_SPOTIFY,
}
